# Generated by Django 4.2.7 on 2023-11-29 17:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("categories", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="color",
            field=models.CharField(default="#FFFFFF", max_length=100),
        ),
    ]
