# Generated by Django 4.2.7 on 2023-11-29 17:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("categories", "0002_alter_category_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="color",
            field=models.CharField(max_length=100),
        ),
    ]
