# Generated by Django 4.2.7 on 2023-12-01 13:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("categories", "0004_alter_category_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="luminance",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
