# Generated by Django 4.2.7 on 2023-12-01 13:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("categories", "0005_category_luminance"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="luminance",
        ),
    ]
