# Generated by Django 4.2.7 on 2023-12-04 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='notification_time',
            field=models.IntegerField(choices=[(1, '1 minuto'), (5, '5 minutos'), (15, '15 minutos'), (30, '30 minutos'), (60, '1 hora'), (180, '3 horas'), (1440, '1 dia'), (10080, '1 semana')], default=1440),
        ),
        migrations.AddField(
            model_name='task',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
